[package]
name = "keen4-flyweight"
version = "0.1.0"
authors = ["Jim Keener <jim@jimkeener.com>"]
edition = "2018"

[build-dependencies]
lalrpop = { version = "0.19", features = ["lexer"] }

[dependencies]
lalrpop-util = "0.19"
regex = "1"
